#-------------------------------
# General Site Settings

title: 立夏时分
description:
logo: # You can add own logo. For example '/images/logo.png'.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iamlixia.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: 立夏
  image: '/images/15.jpg'
  avatar: '/images/01.jpg'
  job: Designer
  bio: 企业文化经理，独立运营人，国家生涯规划师，幸福教练 喜欢摄影、手帐、设计等一切关于美的东西


#-------------------------------
# Contact links
# Example of adding a new link to the header - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
contact:
# - {icon: "ion-logo-twitter", link: "https://twitter.com"}
# - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# - {icon: "ion-logo-instagram", link: "https://instagram.com"}
- {icon: "fab fa-weibo", link: "https://www.weibo.com/u/2047835032"}
- {icon: "fas fa-seedling", link: "https://www.xiaohongshu.com/user/profile/5416aad5b4c4d639ca9e072e"}


#-------------------------------
# Slider Section
slider: true # NOTE - By default, the slider is set to display featured posts. To add featured post to the slider, add the field, featured: true in the YAML front matter block. If you do not want to use the slider, leave the slider field empty.

# For example:
# ---
# layout: post
# featured: true
# ---

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
userID: 6716400487
accessToken: 6716400487.1677ed0.4fae51c47bc544a895b81756a7d0c477


#-------------------------------
# Google Analytics
google-analytics: 'UA-100835831-1' # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed